//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class ConnectCloseMsg : MessageBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ConnectCloseMsg(global::System.IntPtr cPtr, bool cMemoryOwn) : base(stark_matchmakingPINVOKE.ConnectCloseMsg_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConnectCloseMsg obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_ConnectCloseMsg(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public int close_reason {
    set {
      stark_matchmakingPINVOKE.ConnectCloseMsg_close_reason_set(swigCPtr, value);
    } 
    get {
      int ret = stark_matchmakingPINVOKE.ConnectCloseMsg_close_reason_get(swigCPtr);
      return ret;
    } 
  }

  public ConnectCloseMsg() : this(stark_matchmakingPINVOKE.new_ConnectCloseMsg(), true) {
  }

}

}
