//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class EventBaseInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EventBaseInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EventBaseInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~EventBaseInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_EventBaseInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int eventType {
    set {
      stark_matchmakingPINVOKE.EventBaseInfo_eventType_set(swigCPtr, value);
    } 
    get {
      int ret = stark_matchmakingPINVOKE.EventBaseInfo_eventType_get(swigCPtr);
      return ret;
    } 
  }

  public EventBaseData ptrData {
    set {
      stark_matchmakingPINVOKE.EventBaseInfo_ptrData_set(swigCPtr, EventBaseData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.EventBaseInfo_ptrData_get(swigCPtr);
      EventBaseData ret = (cPtr == global::System.IntPtr.Zero) ? null : new EventBaseData(cPtr, false);
      return ret;
    } 
  }

  public EventBaseInfo() : this(stark_matchmakingPINVOKE.new_EventBaseInfo(), true) {
  }

}

}
