//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class MatchmakingOptions : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MatchmakingOptions(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MatchmakingOptions obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MatchmakingOptions() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_MatchmakingOptions(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string custom_matchmaking_policy_name {
    set {
      stark_matchmakingPINVOKE.MatchmakingOptions_custom_matchmaking_policy_name_set(swigCPtr, value);
      if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = stark_matchmakingPINVOKE.MatchmakingOptions_custom_matchmaking_policy_name_get(swigCPtr);
      if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Map_string_string filters {
    set {
      stark_matchmakingPINVOKE.MatchmakingOptions_filters_set(swigCPtr, Map_string_string.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.MatchmakingOptions_filters_get(swigCPtr);
      Map_string_string ret = (cPtr == global::System.IntPtr.Zero) ? null : new Map_string_string(cPtr, false);
      return ret;
    } 
  }

  public bool createNewOne {
    set {
      stark_matchmakingPINVOKE.MatchmakingOptions_createNewOne_set(swigCPtr, value);
    } 
    get {
      bool ret = stark_matchmakingPINVOKE.MatchmakingOptions_createNewOne_get(swigCPtr);
      return ret;
    } 
  }

  public bool matchAndjoinImmediately {
    set {
      stark_matchmakingPINVOKE.MatchmakingOptions_matchAndjoinImmediately_set(swigCPtr, value);
    } 
    get {
      bool ret = stark_matchmakingPINVOKE.MatchmakingOptions_matchAndjoinImmediately_get(swigCPtr);
      return ret;
    } 
  }

  public CreateRoomOption createRoomOption {
    set {
      stark_matchmakingPINVOKE.MatchmakingOptions_createRoomOption_set(swigCPtr, CreateRoomOption.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.MatchmakingOptions_createRoomOption_get(swigCPtr);
      CreateRoomOption ret = (cPtr == global::System.IntPtr.Zero) ? null : new CreateRoomOption(cPtr, false);
      return ret;
    } 
  }

  public bool need_ds {
    set {
      stark_matchmakingPINVOKE.MatchmakingOptions_need_ds_set(swigCPtr, value);
    } 
    get {
      bool ret = stark_matchmakingPINVOKE.MatchmakingOptions_need_ds_get(swigCPtr);
      return ret;
    } 
  }

  public MatchmakingOptions() : this(stark_matchmakingPINVOKE.new_MatchmakingOptions(), true) {
  }

}

}
