//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class Message : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Message(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Message obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Message() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_Message(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int msg_type {
    set {
      stark_matchmakingPINVOKE.Message_msg_type_set(swigCPtr, value);
    } 
    get {
      int ret = stark_matchmakingPINVOKE.Message_msg_type_get(swigCPtr);
      return ret;
    } 
  }

  public MessageBase ptr_data {
    set {
      stark_matchmakingPINVOKE.Message_ptr_data_set(swigCPtr, MessageBase.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.Message_ptr_data_get(swigCPtr);
      MessageBase ret = (cPtr == global::System.IntPtr.Zero) ? null : new MessageBase(cPtr, false);
      return ret;
    } 
  }

  public ulong request_id {
    set {
      stark_matchmakingPINVOKE.Message_request_id_set(swigCPtr, value);
    } 
    get {
      ulong ret = stark_matchmakingPINVOKE.Message_request_id_get(swigCPtr);
      return ret;
    } 
  }

  public ErrorInfo err {
    set {
      stark_matchmakingPINVOKE.Message_err_set(swigCPtr, ErrorInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.Message_err_get(swigCPtr);
      ErrorInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new ErrorInfo(cPtr, false);
      return ret;
    } 
  }

  public Message() : this(stark_matchmakingPINVOKE.new_Message(), true) {
  }

}

}
