//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class PlayerCurrentInfoMsg : MessageBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal PlayerCurrentInfoMsg(global::System.IntPtr cPtr, bool cMemoryOwn) : base(stark_matchmakingPINVOKE.PlayerCurrentInfoMsg_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PlayerCurrentInfoMsg obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_PlayerCurrentInfoMsg(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public PlayerCurrentInfoMsg() : this(stark_matchmakingPINVOKE.new_PlayerCurrentInfoMsg(), true) {
  }

  public Vec_Room room_list {
    set {
      stark_matchmakingPINVOKE.PlayerCurrentInfoMsg_room_list_set(swigCPtr, Vec_Room.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.PlayerCurrentInfoMsg_room_list_get(swigCPtr);
      Vec_Room ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vec_Room(cPtr, false);
      return ret;
    } 
  }

}

}
