//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class RoomMeteDataUpdateResult : MessageBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal RoomMeteDataUpdateResult(global::System.IntPtr cPtr, bool cMemoryOwn) : base(stark_matchmakingPINVOKE.RoomMeteDataUpdateResult_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RoomMeteDataUpdateResult obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_RoomMeteDataUpdateResult(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public ulong room_id {
    set {
      stark_matchmakingPINVOKE.RoomMeteDataUpdateResult_room_id_set(swigCPtr, value);
    } 
    get {
      ulong ret = stark_matchmakingPINVOKE.RoomMeteDataUpdateResult_room_id_get(swigCPtr);
      return ret;
    } 
  }

  public ulong changer_id {
    set {
      stark_matchmakingPINVOKE.RoomMeteDataUpdateResult_changer_id_set(swigCPtr, value);
    } 
    get {
      ulong ret = stark_matchmakingPINVOKE.RoomMeteDataUpdateResult_changer_id_get(swigCPtr);
      return ret;
    } 
  }

  public MetaData changed_meta_data {
    set {
      stark_matchmakingPINVOKE.RoomMeteDataUpdateResult_changed_meta_data_set(swigCPtr, MetaData.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.RoomMeteDataUpdateResult_changed_meta_data_get(swigCPtr);
      MetaData ret = (cPtr == global::System.IntPtr.Zero) ? null : new MetaData(cPtr, false);
      return ret;
    } 
  }

  public RoomMeteDataUpdateResult() : this(stark_matchmakingPINVOKE.new_RoomMeteDataUpdateResult(), true) {
  }

}

}
