//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class RoomSnapShot : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal RoomSnapShot(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RoomSnapShot obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~RoomSnapShot() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_RoomSnapShot(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ulong room_id {
    set {
      stark_matchmakingPINVOKE.RoomSnapShot_room_id_set(swigCPtr, value);
    } 
    get {
      ulong ret = stark_matchmakingPINVOKE.RoomSnapShot_room_id_get(swigCPtr);
      return ret;
    } 
  }

  public uint max_user_num {
    set {
      stark_matchmakingPINVOKE.RoomSnapShot_max_user_num_set(swigCPtr, value);
    } 
    get {
      uint ret = stark_matchmakingPINVOKE.RoomSnapShot_max_user_num_get(swigCPtr);
      return ret;
    } 
  }

  public uint cur_user_num {
    set {
      stark_matchmakingPINVOKE.RoomSnapShot_cur_user_num_set(swigCPtr, value);
    } 
    get {
      uint ret = stark_matchmakingPINVOKE.RoomSnapShot_cur_user_num_get(swigCPtr);
      return ret;
    } 
  }

  public RoomSnapShot() : this(stark_matchmakingPINVOKE.new_RoomSnapShot(), true) {
  }

}

}
