//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class RoomInfoMsg : MessageBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal RoomInfoMsg(global::System.IntPtr cPtr, bool cMemoryOwn) : base(stark_matchmakingPINVOKE.RoomInfoMsg_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RoomInfoMsg obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_RoomInfoMsg(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public RoomInfoMsg() : this(stark_matchmakingPINVOKE.new_RoomInfoMsg(), true) {
  }

  public ulong room_id {
    set {
      stark_matchmakingPINVOKE.RoomInfoMsg_room_id_set(swigCPtr, value);
    } 
    get {
      ulong ret = stark_matchmakingPINVOKE.RoomInfoMsg_room_id_get(swigCPtr);
      return ret;
    } 
  }

  public ulong owner_id {
    set {
      stark_matchmakingPINVOKE.RoomInfoMsg_owner_id_set(swigCPtr, value);
    } 
    get {
      ulong ret = stark_matchmakingPINVOKE.RoomInfoMsg_owner_id_get(swigCPtr);
      return ret;
    } 
  }

  public int cur_user_num {
    set {
      stark_matchmakingPINVOKE.RoomInfoMsg_cur_user_num_set(swigCPtr, value);
    } 
    get {
      int ret = stark_matchmakingPINVOKE.RoomInfoMsg_cur_user_num_get(swigCPtr);
      return ret;
    } 
  }

  public int max_user_num {
    set {
      stark_matchmakingPINVOKE.RoomInfoMsg_max_user_num_set(swigCPtr, value);
    } 
    get {
      int ret = stark_matchmakingPINVOKE.RoomInfoMsg_max_user_num_get(swigCPtr);
      return ret;
    } 
  }

  public Vec_ulong users {
    set {
      stark_matchmakingPINVOKE.RoomInfoMsg_users_set(swigCPtr, Vec_ulong.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.RoomInfoMsg_users_get(swigCPtr);
      Vec_ulong ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vec_ulong(cPtr, false);
      return ret;
    } 
  }

  public Map_string_string meta_data {
    set {
      stark_matchmakingPINVOKE.RoomInfoMsg_meta_data_set(swigCPtr, Map_string_string.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.RoomInfoMsg_meta_data_get(swigCPtr);
      Map_string_string ret = (cPtr == global::System.IntPtr.Zero) ? null : new Map_string_string(cPtr, false);
      return ret;
    } 
  }

  public DedicatedServer ds_info {
    set {
      stark_matchmakingPINVOKE.RoomInfoMsg_ds_info_set(swigCPtr, DedicatedServer.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = stark_matchmakingPINVOKE.RoomInfoMsg_ds_info_get(swigCPtr);
      DedicatedServer ret = (cPtr == global::System.IntPtr.Zero) ? null : new DedicatedServer(cPtr, false);
      return ret;
    } 
  }

}

}
