//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace StarkMatchmaking {

public class Vec_long : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<long>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Vec_long(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Vec_long obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Vec_long() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          stark_matchmakingPINVOKE.delete_Vec_long(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public Vec_long(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (long element in c) {
      this.Add(element);
    }
  }

  public Vec_long(global::System.Collections.Generic.IEnumerable<long> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (long element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public long this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(long[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(long[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, long[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public long[] ToArray() {
    long[] array = new long[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<long> global::System.Collections.Generic.IEnumerable<long>.GetEnumerator() {
    return new Vec_longEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new Vec_longEnumerator(this);
  }

  public Vec_longEnumerator GetEnumerator() {
    return new Vec_longEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class Vec_longEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<long>
  {
    private Vec_long collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public Vec_longEnumerator(Vec_long collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public long Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (long)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    stark_matchmakingPINVOKE.Vec_long_Clear(swigCPtr);
  }

  public void Add(long x) {
    stark_matchmakingPINVOKE.Vec_long_Add(swigCPtr, x);
  }

  private uint size() {
    uint ret = stark_matchmakingPINVOKE.Vec_long_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = stark_matchmakingPINVOKE.Vec_long_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    stark_matchmakingPINVOKE.Vec_long_reserve(swigCPtr, n);
  }

  public Vec_long() : this(stark_matchmakingPINVOKE.new_Vec_long__SWIG_0(), true) {
  }

  public Vec_long(Vec_long other) : this(stark_matchmakingPINVOKE.new_Vec_long__SWIG_1(Vec_long.getCPtr(other)), true) {
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec_long(int capacity) : this(stark_matchmakingPINVOKE.new_Vec_long__SWIG_2(capacity), true) {
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  private long getitemcopy(int index) {
    long ret = stark_matchmakingPINVOKE.Vec_long_getitemcopy(swigCPtr, index);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private long getitem(int index) {
    long ret = stark_matchmakingPINVOKE.Vec_long_getitem(swigCPtr, index);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, long val) {
    stark_matchmakingPINVOKE.Vec_long_setitem(swigCPtr, index, val);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(Vec_long values) {
    stark_matchmakingPINVOKE.Vec_long_AddRange(swigCPtr, Vec_long.getCPtr(values));
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public Vec_long GetRange(int index, int count) {
    global::System.IntPtr cPtr = stark_matchmakingPINVOKE.Vec_long_GetRange(swigCPtr, index, count);
    Vec_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vec_long(cPtr, true);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, long x) {
    stark_matchmakingPINVOKE.Vec_long_Insert(swigCPtr, index, x);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, Vec_long values) {
    stark_matchmakingPINVOKE.Vec_long_InsertRange(swigCPtr, index, Vec_long.getCPtr(values));
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    stark_matchmakingPINVOKE.Vec_long_RemoveAt(swigCPtr, index);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    stark_matchmakingPINVOKE.Vec_long_RemoveRange(swigCPtr, index, count);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Vec_long Repeat(long value, int count) {
    global::System.IntPtr cPtr = stark_matchmakingPINVOKE.Vec_long_Repeat(value, count);
    Vec_long ret = (cPtr == global::System.IntPtr.Zero) ? null : new Vec_long(cPtr, true);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    stark_matchmakingPINVOKE.Vec_long_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    stark_matchmakingPINVOKE.Vec_long_Reverse__SWIG_1(swigCPtr, index, count);
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, Vec_long values) {
    stark_matchmakingPINVOKE.Vec_long_SetRange(swigCPtr, index, Vec_long.getCPtr(values));
    if (stark_matchmakingPINVOKE.SWIGPendingException.Pending) throw stark_matchmakingPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(long value) {
    bool ret = stark_matchmakingPINVOKE.Vec_long_Contains(swigCPtr, value);
    return ret;
  }

  public int IndexOf(long value) {
    int ret = stark_matchmakingPINVOKE.Vec_long_IndexOf(swigCPtr, value);
    return ret;
  }

  public int LastIndexOf(long value) {
    int ret = stark_matchmakingPINVOKE.Vec_long_LastIndexOf(swigCPtr, value);
    return ret;
  }

  public bool Remove(long value) {
    bool ret = stark_matchmakingPINVOKE.Vec_long_Remove(swigCPtr, value);
    return ret;
  }

}

}
